site_name: TinyDataTable
site_description: Unity用の軽量で高速なデータテーブルパッケージ
site_author: sakana3
site_url: https://sakana3.github.io/TinyDataTable/
theme:
  name: material
  language: ja
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.tracking
    - navigation.top
    - search.suggest
    - search.highlight
    - content.code.copy
    - content.code.annotate
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: light-green
      accent: light-green
      toggle:
        icon: material/brightness-7
        name: ダークモードへ切り替え
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: indigo
      accent: cyan
      toggle:
        icon: material/brightness-4
        name: ライトモードへ切り替え
  font:
    text: Roboto
    code: JetBrains Mono

repo_name: sakana3/TinyDataTable
repo_url: https://github.com/sakana3/TinyDataTable
edit_uri: edit/main/docs/

nav:
  - ホーム: index.md
  - 導入方法: installation.md
  - 基本的な使い方: usage.md
  - ライセンス: license.md

plugins:
  - search

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.tabbed:
      alternate_style: true        
        
extra_css:
  - stylesheets/custom.css
