// [TYNY_DATA_TABLE][1.0.0]
// This code is generated by TinyDataTable.
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
using System;
using System.Linq;
using System.Collections.Generic;

namespace TinyDataTable
{
    public static partial class VariableStructBuilder
    {
        public static int TypeCount => 32;

        public static Type  GetType(int numField)
        {
            Type type = numField switch
            {
                0 => typeof(VariableStruct),
                1 => typeof(VariableStruct<>),
                2 => typeof(VariableStruct<,>),
                3 => typeof(VariableStruct<,,>),
                4 => typeof(VariableStruct<,,,>),
                5 => typeof(VariableStruct<,,,,>),
                6 => typeof(VariableStruct<,,,,,>),
                7 => typeof(VariableStruct<,,,,,,>),
                8 => typeof(VariableStruct<,,,,,,,>),
                9 => typeof(VariableStruct<,,,,,,,,>),
                10 => typeof(VariableStruct<,,,,,,,,,>),
                11 => typeof(VariableStruct<,,,,,,,,,,>),
                12 => typeof(VariableStruct<,,,,,,,,,,,>),
                13 => typeof(VariableStruct<,,,,,,,,,,,,>),
                14 => typeof(VariableStruct<,,,,,,,,,,,,,>),
                15 => typeof(VariableStruct<,,,,,,,,,,,,,,>),
                16 => typeof(VariableStruct<,,,,,,,,,,,,,,,>),
                17 => typeof(VariableStruct<,,,,,,,,,,,,,,,,>),
                18 => typeof(VariableStruct<,,,,,,,,,,,,,,,,,>),
                19 => typeof(VariableStruct<,,,,,,,,,,,,,,,,,,>),
                20 => typeof(VariableStruct<,,,,,,,,,,,,,,,,,,,>),
                21 => typeof(VariableStruct<,,,,,,,,,,,,,,,,,,,,>),
                22 => typeof(VariableStruct<,,,,,,,,,,,,,,,,,,,,,>),
                23 => typeof(VariableStruct<,,,,,,,,,,,,,,,,,,,,,,>),
                24 => typeof(VariableStruct<,,,,,,,,,,,,,,,,,,,,,,,>),
                25 => typeof(VariableStruct<,,,,,,,,,,,,,,,,,,,,,,,,>),
                26 => typeof(VariableStruct<,,,,,,,,,,,,,,,,,,,,,,,,,>),
                27 => typeof(VariableStruct<,,,,,,,,,,,,,,,,,,,,,,,,,,>),
                28 => typeof(VariableStruct<,,,,,,,,,,,,,,,,,,,,,,,,,,,>),
                29 => typeof(VariableStruct<,,,,,,,,,,,,,,,,,,,,,,,,,,,,>),
                30 => typeof(VariableStruct<,,,,,,,,,,,,,,,,,,,,,,,,,,,,,>),
                31 => typeof(VariableStruct<,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,>),
                32 => typeof(VariableStruct<,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,>),
                _ => throw new IndexOutOfRangeException(),
            };
            return type;
        }
    }

#region VariableStructs
    [Serializable]
    public struct VariableStruct : IVariableStruct
    {
        public RecordHeader header;
        public RecordData[] recordData;

        public RecordHeader Header { set => header = value; get => header; }
        public Type[] GetFieldTypes() => Type.EmptyTypes;
        public IEnumerable<IRecordData> Records => recordData == null ? Array.Empty<IRecordData>() : recordData.OfType<IRecordData>();
        public IRecordData GetRecord(int rowIndex) => recordData[rowIndex];
        public void Iniaialize( RecordDataHeader newHeader ) { recordData = new RecordData[1] { new RecordData() { header = newHeader } }; }

        [Serializable]
        public struct RecordData : IRecordData
        {
            public RecordDataHeader header;
            public RecordDataHeader Header {set => header = value; get => header;}
        }
    }

    [Serializable]
    public struct VariableStruct<T0> : IVariableStruct
    {
        public RecordHeader header;
        public RecordData[] recordData;
        private static Type[] _fieldTypes = new []{typeof(T0)};
        public RecordHeader Header { set => header = value; get => header; }
        public Type[] GetFieldTypes() => _fieldTypes;
        public IEnumerable<IRecordData> Records => recordData == null ? Array.Empty<IRecordData>() : recordData.OfType<IRecordData>();
        public IRecordData GetRecord(int rowIndex) => recordData[rowIndex];

        [Serializable]
        public struct RecordData : IRecordData
        {
            public RecordDataHeader header;
            public RecordDataHeader Header {set => header = value; get => header;}
            public T0 Field0;
        }
    }

    [Serializable]
    public struct VariableStruct<T0,T1> : IVariableStruct
    {
        public RecordHeader header;
        public RecordData[] recordData;
        private static Type[] _fieldTypes = new []{typeof(T0),typeof(T1)};
        public RecordHeader Header { set => header = value; get => header; }
        public Type[] GetFieldTypes() => _fieldTypes;
        public IEnumerable<IRecordData> Records => recordData == null ? Array.Empty<IRecordData>() : recordData.OfType<IRecordData>();
        public IRecordData GetRecord(int rowIndex) => recordData[rowIndex];

        [Serializable]
        public struct RecordData : IRecordData
        {
            public RecordDataHeader header;
            public RecordDataHeader Header {set => header = value; get => header;}
            public T0 Field0;
            public T1 Field1;
        }
    }

    [Serializable]
    public struct VariableStruct<T0,T1,T2> : IVariableStruct
    {
        public RecordHeader header;
        public RecordData[] recordData;
        private static Type[] _fieldTypes = new []{typeof(T0),typeof(T1),typeof(T2)};
        public RecordHeader Header { set => header = value; get => header; }
        public Type[] GetFieldTypes() => _fieldTypes;
        public IEnumerable<IRecordData> Records => recordData == null ? Array.Empty<IRecordData>() : recordData.OfType<IRecordData>();
        public IRecordData GetRecord(int rowIndex) => recordData[rowIndex];

        [Serializable]
        public struct RecordData : IRecordData
        {
            public RecordDataHeader header;
            public RecordDataHeader Header {set => header = value; get => header;}
            public T0 Field0;
            public T1 Field1;
            public T2 Field2;
        }
    }

    [Serializable]
    public struct VariableStruct<T0,T1,T2,T3> : IVariableStruct
    {
        public RecordHeader header;
        public RecordData[] recordData;
        private static Type[] _fieldTypes = new []{typeof(T0),typeof(T1),typeof(T2),typeof(T3)};
        public RecordHeader Header { set => header = value; get => header; }
        public Type[] GetFieldTypes() => _fieldTypes;
        public IEnumerable<IRecordData> Records => recordData == null ? Array.Empty<IRecordData>() : recordData.OfType<IRecordData>();
        public IRecordData GetRecord(int rowIndex) => recordData[rowIndex];

        [Serializable]
        public struct RecordData : IRecordData
        {
            public RecordDataHeader header;
            public RecordDataHeader Header {set => header = value; get => header;}
            public T0 Field0;
            public T1 Field1;
            public T2 Field2;
            public T3 Field3;
        }
    }

    [Serializable]
    public struct VariableStruct<T0,T1,T2,T3,T4> : IVariableStruct
    {
        public RecordHeader header;
        public RecordData[] recordData;
        private static Type[] _fieldTypes = new []{typeof(T0),typeof(T1),typeof(T2),typeof(T3),typeof(T4)};
        public RecordHeader Header { set => header = value; get => header; }
        public Type[] GetFieldTypes() => _fieldTypes;
        public IEnumerable<IRecordData> Records => recordData == null ? Array.Empty<IRecordData>() : recordData.OfType<IRecordData>();
        public IRecordData GetRecord(int rowIndex) => recordData[rowIndex];

        [Serializable]
        public struct RecordData : IRecordData
        {
            public RecordDataHeader header;
            public RecordDataHeader Header {set => header = value; get => header;}
            public T0 Field0;
            public T1 Field1;
            public T2 Field2;
            public T3 Field3;
            public T4 Field4;
        }
    }

    [Serializable]
    public struct VariableStruct<T0,T1,T2,T3,T4,T5> : IVariableStruct
    {
        public RecordHeader header;
        public RecordData[] recordData;
        private static Type[] _fieldTypes = new []{typeof(T0),typeof(T1),typeof(T2),typeof(T3),typeof(T4),typeof(T5)};
        public RecordHeader Header { set => header = value; get => header; }
        public Type[] GetFieldTypes() => _fieldTypes;
        public IEnumerable<IRecordData> Records => recordData == null ? Array.Empty<IRecordData>() : recordData.OfType<IRecordData>();
        public IRecordData GetRecord(int rowIndex) => recordData[rowIndex];

        [Serializable]
        public struct RecordData : IRecordData
        {
            public RecordDataHeader header;
            public RecordDataHeader Header {set => header = value; get => header;}
            public T0 Field0;
            public T1 Field1;
            public T2 Field2;
            public T3 Field3;
            public T4 Field4;
            public T5 Field5;
        }
    }

    [Serializable]
    public struct VariableStruct<T0,T1,T2,T3,T4,T5,T6> : IVariableStruct
    {
        public RecordHeader header;
        public RecordData[] recordData;
        private static Type[] _fieldTypes = new []{typeof(T0),typeof(T1),typeof(T2),typeof(T3),typeof(T4),typeof(T5),typeof(T6)};
        public RecordHeader Header { set => header = value; get => header; }
        public Type[] GetFieldTypes() => _fieldTypes;
        public IEnumerable<IRecordData> Records => recordData == null ? Array.Empty<IRecordData>() : recordData.OfType<IRecordData>();
        public IRecordData GetRecord(int rowIndex) => recordData[rowIndex];

        [Serializable]
        public struct RecordData : IRecordData
        {
            public RecordDataHeader header;
            public RecordDataHeader Header {set => header = value; get => header;}
            public T0 Field0;
            public T1 Field1;
            public T2 Field2;
            public T3 Field3;
            public T4 Field4;
            public T5 Field5;
            public T6 Field6;
        }
    }

    [Serializable]
    public struct VariableStruct<T0,T1,T2,T3,T4,T5,T6,T7> : IVariableStruct
    {
        public RecordHeader header;
        public RecordData[] recordData;
        private static Type[] _fieldTypes = new []{typeof(T0),typeof(T1),typeof(T2),typeof(T3),typeof(T4),typeof(T5),typeof(T6),typeof(T7)};
        public RecordHeader Header { set => header = value; get => header; }
        public Type[] GetFieldTypes() => _fieldTypes;
        public IEnumerable<IRecordData> Records => recordData == null ? Array.Empty<IRecordData>() : recordData.OfType<IRecordData>();
        public IRecordData GetRecord(int rowIndex) => recordData[rowIndex];

        [Serializable]
        public struct RecordData : IRecordData
        {
            public RecordDataHeader header;
            public RecordDataHeader Header {set => header = value; get => header;}
            public T0 Field0;
            public T1 Field1;
            public T2 Field2;
            public T3 Field3;
            public T4 Field4;
            public T5 Field5;
            public T6 Field6;
            public T7 Field7;
        }
    }

    [Serializable]
    public struct VariableStruct<T0,T1,T2,T3,T4,T5,T6,T7,T8> : IVariableStruct
    {
        public RecordHeader header;
        public RecordData[] recordData;
        private static Type[] _fieldTypes = new []{typeof(T0),typeof(T1),typeof(T2),typeof(T3),typeof(T4),typeof(T5),typeof(T6),typeof(T7),typeof(T8)};
        public RecordHeader Header { set => header = value; get => header; }
        public Type[] GetFieldTypes() => _fieldTypes;
        public IEnumerable<IRecordData> Records => recordData == null ? Array.Empty<IRecordData>() : recordData.OfType<IRecordData>();
        public IRecordData GetRecord(int rowIndex) => recordData[rowIndex];

        [Serializable]
        public struct RecordData : IRecordData
        {
            public RecordDataHeader header;
            public RecordDataHeader Header {set => header = value; get => header;}
            public T0 Field0;
            public T1 Field1;
            public T2 Field2;
            public T3 Field3;
            public T4 Field4;
            public T5 Field5;
            public T6 Field6;
            public T7 Field7;
            public T8 Field8;
        }
    }

    [Serializable]
    public struct VariableStruct<T0,T1,T2,T3,T4,T5,T6,T7,T8,T9> : IVariableStruct
    {
        public RecordHeader header;
        public RecordData[] recordData;
        private static Type[] _fieldTypes = new []{typeof(T0),typeof(T1),typeof(T2),typeof(T3),typeof(T4),typeof(T5),typeof(T6),typeof(T7),typeof(T8),typeof(T9)};
        public RecordHeader Header { set => header = value; get => header; }
        public Type[] GetFieldTypes() => _fieldTypes;
        public IEnumerable<IRecordData> Records => recordData == null ? Array.Empty<IRecordData>() : recordData.OfType<IRecordData>();
        public IRecordData GetRecord(int rowIndex) => recordData[rowIndex];

        [Serializable]
        public struct RecordData : IRecordData
        {
            public RecordDataHeader header;
            public RecordDataHeader Header {set => header = value; get => header;}
            public T0 Field0;
            public T1 Field1;
            public T2 Field2;
            public T3 Field3;
            public T4 Field4;
            public T5 Field5;
            public T6 Field6;
            public T7 Field7;
            public T8 Field8;
            public T9 Field9;
        }
    }

    [Serializable]
    public struct VariableStruct<T0,T1,T2,T3,T4,T5,T6,T7,T8,T9,T10> : IVariableStruct
    {
        public RecordHeader header;
        public RecordData[] recordData;
        private static Type[] _fieldTypes = new []{typeof(T0),typeof(T1),typeof(T2),typeof(T3),typeof(T4),typeof(T5),typeof(T6),typeof(T7),typeof(T8),typeof(T9),typeof(T10)};
        public RecordHeader Header { set => header = value; get => header; }
        public Type[] GetFieldTypes() => _fieldTypes;
        public IEnumerable<IRecordData> Records => recordData == null ? Array.Empty<IRecordData>() : recordData.OfType<IRecordData>();
        public IRecordData GetRecord(int rowIndex) => recordData[rowIndex];

        [Serializable]
        public struct RecordData : IRecordData
        {
            public RecordDataHeader header;
            public RecordDataHeader Header {set => header = value; get => header;}
            public T0 Field0;
            public T1 Field1;
            public T2 Field2;
            public T3 Field3;
            public T4 Field4;
            public T5 Field5;
            public T6 Field6;
            public T7 Field7;
            public T8 Field8;
            public T9 Field9;
            public T10 Field10;
        }
    }

    [Serializable]
    public struct VariableStruct<T0,T1,T2,T3,T4,T5,T6,T7,T8,T9,T10,T11> : IVariableStruct
    {
        public RecordHeader header;
        public RecordData[] recordData;
        private static Type[] _fieldTypes = new []{typeof(T0),typeof(T1),typeof(T2),typeof(T3),typeof(T4),typeof(T5),typeof(T6),typeof(T7),typeof(T8),typeof(T9),typeof(T10),typeof(T11)};
        public RecordHeader Header { set => header = value; get => header; }
        public Type[] GetFieldTypes() => _fieldTypes;
        public IEnumerable<IRecordData> Records => recordData == null ? Array.Empty<IRecordData>() : recordData.OfType<IRecordData>();
        public IRecordData GetRecord(int rowIndex) => recordData[rowIndex];

        [Serializable]
        public struct RecordData : IRecordData
        {
            public RecordDataHeader header;
            public RecordDataHeader Header {set => header = value; get => header;}
            public T0 Field0;
            public T1 Field1;
            public T2 Field2;
            public T3 Field3;
            public T4 Field4;
            public T5 Field5;
            public T6 Field6;
            public T7 Field7;
            public T8 Field8;
            public T9 Field9;
            public T10 Field10;
            public T11 Field11;
        }
    }

    [Serializable]
    public struct VariableStruct<T0,T1,T2,T3,T4,T5,T6,T7,T8,T9,T10,T11,T12> : IVariableStruct
    {
        public RecordHeader header;
        public RecordData[] recordData;
        private static Type[] _fieldTypes = new []{typeof(T0),typeof(T1),typeof(T2),typeof(T3),typeof(T4),typeof(T5),typeof(T6),typeof(T7),typeof(T8),typeof(T9),typeof(T10),typeof(T11),typeof(T12)};
        public RecordHeader Header { set => header = value; get => header; }
        public Type[] GetFieldTypes() => _fieldTypes;
        public IEnumerable<IRecordData> Records => recordData == null ? Array.Empty<IRecordData>() : recordData.OfType<IRecordData>();
        public IRecordData GetRecord(int rowIndex) => recordData[rowIndex];

        [Serializable]
        public struct RecordData : IRecordData
        {
            public RecordDataHeader header;
            public RecordDataHeader Header {set => header = value; get => header;}
            public T0 Field0;
            public T1 Field1;
            public T2 Field2;
            public T3 Field3;
            public T4 Field4;
            public T5 Field5;
            public T6 Field6;
            public T7 Field7;
            public T8 Field8;
            public T9 Field9;
            public T10 Field10;
            public T11 Field11;
            public T12 Field12;
        }
    }

    [Serializable]
    public struct VariableStruct<T0,T1,T2,T3,T4,T5,T6,T7,T8,T9,T10,T11,T12,T13> : IVariableStruct
    {
        public RecordHeader header;
        public RecordData[] recordData;
        private static Type[] _fieldTypes = new []{typeof(T0),typeof(T1),typeof(T2),typeof(T3),typeof(T4),typeof(T5),typeof(T6),typeof(T7),typeof(T8),typeof(T9),typeof(T10),typeof(T11),typeof(T12),typeof(T13)};
        public RecordHeader Header { set => header = value; get => header; }
        public Type[] GetFieldTypes() => _fieldTypes;
        public IEnumerable<IRecordData> Records => recordData == null ? Array.Empty<IRecordData>() : recordData.OfType<IRecordData>();
        public IRecordData GetRecord(int rowIndex) => recordData[rowIndex];

        [Serializable]
        public struct RecordData : IRecordData
        {
            public RecordDataHeader header;
            public RecordDataHeader Header {set => header = value; get => header;}
            public T0 Field0;
            public T1 Field1;
            public T2 Field2;
            public T3 Field3;
            public T4 Field4;
            public T5 Field5;
            public T6 Field6;
            public T7 Field7;
            public T8 Field8;
            public T9 Field9;
            public T10 Field10;
            public T11 Field11;
            public T12 Field12;
            public T13 Field13;
        }
    }

    [Serializable]
    public struct VariableStruct<T0,T1,T2,T3,T4,T5,T6,T7,T8,T9,T10,T11,T12,T13,T14> : IVariableStruct
    {
        public RecordHeader header;
        public RecordData[] recordData;
        private static Type[] _fieldTypes = new []{typeof(T0),typeof(T1),typeof(T2),typeof(T3),typeof(T4),typeof(T5),typeof(T6),typeof(T7),typeof(T8),typeof(T9),typeof(T10),typeof(T11),typeof(T12),typeof(T13),typeof(T14)};
        public RecordHeader Header { set => header = value; get => header; }
        public Type[] GetFieldTypes() => _fieldTypes;
        public IEnumerable<IRecordData> Records => recordData == null ? Array.Empty<IRecordData>() : recordData.OfType<IRecordData>();
        public IRecordData GetRecord(int rowIndex) => recordData[rowIndex];

        [Serializable]
        public struct RecordData : IRecordData
        {
            public RecordDataHeader header;
            public RecordDataHeader Header {set => header = value; get => header;}
            public T0 Field0;
            public T1 Field1;
            public T2 Field2;
            public T3 Field3;
            public T4 Field4;
            public T5 Field5;
            public T6 Field6;
            public T7 Field7;
            public T8 Field8;
            public T9 Field9;
            public T10 Field10;
            public T11 Field11;
            public T12 Field12;
            public T13 Field13;
            public T14 Field14;
        }
    }

    [Serializable]
    public struct VariableStruct<T0,T1,T2,T3,T4,T5,T6,T7,T8,T9,T10,T11,T12,T13,T14,T15> : IVariableStruct
    {
        public RecordHeader header;
        public RecordData[] recordData;
        private static Type[] _fieldTypes = new []{typeof(T0),typeof(T1),typeof(T2),typeof(T3),typeof(T4),typeof(T5),typeof(T6),typeof(T7),typeof(T8),typeof(T9),typeof(T10),typeof(T11),typeof(T12),typeof(T13),typeof(T14),typeof(T15)};
        public RecordHeader Header { set => header = value; get => header; }
        public Type[] GetFieldTypes() => _fieldTypes;
        public IEnumerable<IRecordData> Records => recordData == null ? Array.Empty<IRecordData>() : recordData.OfType<IRecordData>();
        public IRecordData GetRecord(int rowIndex) => recordData[rowIndex];

        [Serializable]
        public struct RecordData : IRecordData
        {
            public RecordDataHeader header;
            public RecordDataHeader Header {set => header = value; get => header;}
            public T0 Field0;
            public T1 Field1;
            public T2 Field2;
            public T3 Field3;
            public T4 Field4;
            public T5 Field5;
            public T6 Field6;
            public T7 Field7;
            public T8 Field8;
            public T9 Field9;
            public T10 Field10;
            public T11 Field11;
            public T12 Field12;
            public T13 Field13;
            public T14 Field14;
            public T15 Field15;
        }
    }

    [Serializable]
    public struct VariableStruct<T0,T1,T2,T3,T4,T5,T6,T7,T8,T9,T10,T11,T12,T13,T14,T15,T16> : IVariableStruct
    {
        public RecordHeader header;
        public RecordData[] recordData;
        private static Type[] _fieldTypes = new []{typeof(T0),typeof(T1),typeof(T2),typeof(T3),typeof(T4),typeof(T5),typeof(T6),typeof(T7),typeof(T8),typeof(T9),typeof(T10),typeof(T11),typeof(T12),typeof(T13),typeof(T14),typeof(T15),typeof(T16)};
        public RecordHeader Header { set => header = value; get => header; }
        public Type[] GetFieldTypes() => _fieldTypes;
        public IEnumerable<IRecordData> Records => recordData == null ? Array.Empty<IRecordData>() : recordData.OfType<IRecordData>();
        public IRecordData GetRecord(int rowIndex) => recordData[rowIndex];

        [Serializable]
        public struct RecordData : IRecordData
        {
            public RecordDataHeader header;
            public RecordDataHeader Header {set => header = value; get => header;}
            public T0 Field0;
            public T1 Field1;
            public T2 Field2;
            public T3 Field3;
            public T4 Field4;
            public T5 Field5;
            public T6 Field6;
            public T7 Field7;
            public T8 Field8;
            public T9 Field9;
            public T10 Field10;
            public T11 Field11;
            public T12 Field12;
            public T13 Field13;
            public T14 Field14;
            public T15 Field15;
            public T16 Field16;
        }
    }

    [Serializable]
    public struct VariableStruct<T0,T1,T2,T3,T4,T5,T6,T7,T8,T9,T10,T11,T12,T13,T14,T15,T16,T17> : IVariableStruct
    {
        public RecordHeader header;
        public RecordData[] recordData;
        private static Type[] _fieldTypes = new []{typeof(T0),typeof(T1),typeof(T2),typeof(T3),typeof(T4),typeof(T5),typeof(T6),typeof(T7),typeof(T8),typeof(T9),typeof(T10),typeof(T11),typeof(T12),typeof(T13),typeof(T14),typeof(T15),typeof(T16),typeof(T17)};
        public RecordHeader Header { set => header = value; get => header; }
        public Type[] GetFieldTypes() => _fieldTypes;
        public IEnumerable<IRecordData> Records => recordData == null ? Array.Empty<IRecordData>() : recordData.OfType<IRecordData>();
        public IRecordData GetRecord(int rowIndex) => recordData[rowIndex];

        [Serializable]
        public struct RecordData : IRecordData
        {
            public RecordDataHeader header;
            public RecordDataHeader Header {set => header = value; get => header;}
            public T0 Field0;
            public T1 Field1;
            public T2 Field2;
            public T3 Field3;
            public T4 Field4;
            public T5 Field5;
            public T6 Field6;
            public T7 Field7;
            public T8 Field8;
            public T9 Field9;
            public T10 Field10;
            public T11 Field11;
            public T12 Field12;
            public T13 Field13;
            public T14 Field14;
            public T15 Field15;
            public T16 Field16;
            public T17 Field17;
        }
    }

    [Serializable]
    public struct VariableStruct<T0,T1,T2,T3,T4,T5,T6,T7,T8,T9,T10,T11,T12,T13,T14,T15,T16,T17,T18> : IVariableStruct
    {
        public RecordHeader header;
        public RecordData[] recordData;
        private static Type[] _fieldTypes = new []{typeof(T0),typeof(T1),typeof(T2),typeof(T3),typeof(T4),typeof(T5),typeof(T6),typeof(T7),typeof(T8),typeof(T9),typeof(T10),typeof(T11),typeof(T12),typeof(T13),typeof(T14),typeof(T15),typeof(T16),typeof(T17),typeof(T18)};
        public RecordHeader Header { set => header = value; get => header; }
        public Type[] GetFieldTypes() => _fieldTypes;
        public IEnumerable<IRecordData> Records => recordData == null ? Array.Empty<IRecordData>() : recordData.OfType<IRecordData>();
        public IRecordData GetRecord(int rowIndex) => recordData[rowIndex];

        [Serializable]
        public struct RecordData : IRecordData
        {
            public RecordDataHeader header;
            public RecordDataHeader Header {set => header = value; get => header;}
            public T0 Field0;
            public T1 Field1;
            public T2 Field2;
            public T3 Field3;
            public T4 Field4;
            public T5 Field5;
            public T6 Field6;
            public T7 Field7;
            public T8 Field8;
            public T9 Field9;
            public T10 Field10;
            public T11 Field11;
            public T12 Field12;
            public T13 Field13;
            public T14 Field14;
            public T15 Field15;
            public T16 Field16;
            public T17 Field17;
            public T18 Field18;
        }
    }

    [Serializable]
    public struct VariableStruct<T0,T1,T2,T3,T4,T5,T6,T7,T8,T9,T10,T11,T12,T13,T14,T15,T16,T17,T18,T19> : IVariableStruct
    {
        public RecordHeader header;
        public RecordData[] recordData;
        private static Type[] _fieldTypes = new []{typeof(T0),typeof(T1),typeof(T2),typeof(T3),typeof(T4),typeof(T5),typeof(T6),typeof(T7),typeof(T8),typeof(T9),typeof(T10),typeof(T11),typeof(T12),typeof(T13),typeof(T14),typeof(T15),typeof(T16),typeof(T17),typeof(T18),typeof(T19)};
        public RecordHeader Header { set => header = value; get => header; }
        public Type[] GetFieldTypes() => _fieldTypes;
        public IEnumerable<IRecordData> Records => recordData == null ? Array.Empty<IRecordData>() : recordData.OfType<IRecordData>();
        public IRecordData GetRecord(int rowIndex) => recordData[rowIndex];

        [Serializable]
        public struct RecordData : IRecordData
        {
            public RecordDataHeader header;
            public RecordDataHeader Header {set => header = value; get => header;}
            public T0 Field0;
            public T1 Field1;
            public T2 Field2;
            public T3 Field3;
            public T4 Field4;
            public T5 Field5;
            public T6 Field6;
            public T7 Field7;
            public T8 Field8;
            public T9 Field9;
            public T10 Field10;
            public T11 Field11;
            public T12 Field12;
            public T13 Field13;
            public T14 Field14;
            public T15 Field15;
            public T16 Field16;
            public T17 Field17;
            public T18 Field18;
            public T19 Field19;
        }
    }

    [Serializable]
    public struct VariableStruct<T0,T1,T2,T3,T4,T5,T6,T7,T8,T9,T10,T11,T12,T13,T14,T15,T16,T17,T18,T19,T20> : IVariableStruct
    {
        public RecordHeader header;
        public RecordData[] recordData;
        private static Type[] _fieldTypes = new []{typeof(T0),typeof(T1),typeof(T2),typeof(T3),typeof(T4),typeof(T5),typeof(T6),typeof(T7),typeof(T8),typeof(T9),typeof(T10),typeof(T11),typeof(T12),typeof(T13),typeof(T14),typeof(T15),typeof(T16),typeof(T17),typeof(T18),typeof(T19),typeof(T20)};
        public RecordHeader Header { set => header = value; get => header; }
        public Type[] GetFieldTypes() => _fieldTypes;
        public IEnumerable<IRecordData> Records => recordData == null ? Array.Empty<IRecordData>() : recordData.OfType<IRecordData>();
        public IRecordData GetRecord(int rowIndex) => recordData[rowIndex];

        [Serializable]
        public struct RecordData : IRecordData
        {
            public RecordDataHeader header;
            public RecordDataHeader Header {set => header = value; get => header;}
            public T0 Field0;
            public T1 Field1;
            public T2 Field2;
            public T3 Field3;
            public T4 Field4;
            public T5 Field5;
            public T6 Field6;
            public T7 Field7;
            public T8 Field8;
            public T9 Field9;
            public T10 Field10;
            public T11 Field11;
            public T12 Field12;
            public T13 Field13;
            public T14 Field14;
            public T15 Field15;
            public T16 Field16;
            public T17 Field17;
            public T18 Field18;
            public T19 Field19;
            public T20 Field20;
        }
    }

    [Serializable]
    public struct VariableStruct<T0,T1,T2,T3,T4,T5,T6,T7,T8,T9,T10,T11,T12,T13,T14,T15,T16,T17,T18,T19,T20,T21> : IVariableStruct
    {
        public RecordHeader header;
        public RecordData[] recordData;
        private static Type[] _fieldTypes = new []{typeof(T0),typeof(T1),typeof(T2),typeof(T3),typeof(T4),typeof(T5),typeof(T6),typeof(T7),typeof(T8),typeof(T9),typeof(T10),typeof(T11),typeof(T12),typeof(T13),typeof(T14),typeof(T15),typeof(T16),typeof(T17),typeof(T18),typeof(T19),typeof(T20),typeof(T21)};
        public RecordHeader Header { set => header = value; get => header; }
        public Type[] GetFieldTypes() => _fieldTypes;
        public IEnumerable<IRecordData> Records => recordData == null ? Array.Empty<IRecordData>() : recordData.OfType<IRecordData>();
        public IRecordData GetRecord(int rowIndex) => recordData[rowIndex];

        [Serializable]
        public struct RecordData : IRecordData
        {
            public RecordDataHeader header;
            public RecordDataHeader Header {set => header = value; get => header;}
            public T0 Field0;
            public T1 Field1;
            public T2 Field2;
            public T3 Field3;
            public T4 Field4;
            public T5 Field5;
            public T6 Field6;
            public T7 Field7;
            public T8 Field8;
            public T9 Field9;
            public T10 Field10;
            public T11 Field11;
            public T12 Field12;
            public T13 Field13;
            public T14 Field14;
            public T15 Field15;
            public T16 Field16;
            public T17 Field17;
            public T18 Field18;
            public T19 Field19;
            public T20 Field20;
            public T21 Field21;
        }
    }

    [Serializable]
    public struct VariableStruct<T0,T1,T2,T3,T4,T5,T6,T7,T8,T9,T10,T11,T12,T13,T14,T15,T16,T17,T18,T19,T20,T21,T22> : IVariableStruct
    {
        public RecordHeader header;
        public RecordData[] recordData;
        private static Type[] _fieldTypes = new []{typeof(T0),typeof(T1),typeof(T2),typeof(T3),typeof(T4),typeof(T5),typeof(T6),typeof(T7),typeof(T8),typeof(T9),typeof(T10),typeof(T11),typeof(T12),typeof(T13),typeof(T14),typeof(T15),typeof(T16),typeof(T17),typeof(T18),typeof(T19),typeof(T20),typeof(T21),typeof(T22)};
        public RecordHeader Header { set => header = value; get => header; }
        public Type[] GetFieldTypes() => _fieldTypes;
        public IEnumerable<IRecordData> Records => recordData == null ? Array.Empty<IRecordData>() : recordData.OfType<IRecordData>();
        public IRecordData GetRecord(int rowIndex) => recordData[rowIndex];

        [Serializable]
        public struct RecordData : IRecordData
        {
            public RecordDataHeader header;
            public RecordDataHeader Header {set => header = value; get => header;}
            public T0 Field0;
            public T1 Field1;
            public T2 Field2;
            public T3 Field3;
            public T4 Field4;
            public T5 Field5;
            public T6 Field6;
            public T7 Field7;
            public T8 Field8;
            public T9 Field9;
            public T10 Field10;
            public T11 Field11;
            public T12 Field12;
            public T13 Field13;
            public T14 Field14;
            public T15 Field15;
            public T16 Field16;
            public T17 Field17;
            public T18 Field18;
            public T19 Field19;
            public T20 Field20;
            public T21 Field21;
            public T22 Field22;
        }
    }

    [Serializable]
    public struct VariableStruct<T0,T1,T2,T3,T4,T5,T6,T7,T8,T9,T10,T11,T12,T13,T14,T15,T16,T17,T18,T19,T20,T21,T22,T23> : IVariableStruct
    {
        public RecordHeader header;
        public RecordData[] recordData;
        private static Type[] _fieldTypes = new []{typeof(T0),typeof(T1),typeof(T2),typeof(T3),typeof(T4),typeof(T5),typeof(T6),typeof(T7),typeof(T8),typeof(T9),typeof(T10),typeof(T11),typeof(T12),typeof(T13),typeof(T14),typeof(T15),typeof(T16),typeof(T17),typeof(T18),typeof(T19),typeof(T20),typeof(T21),typeof(T22),typeof(T23)};
        public RecordHeader Header { set => header = value; get => header; }
        public Type[] GetFieldTypes() => _fieldTypes;
        public IEnumerable<IRecordData> Records => recordData == null ? Array.Empty<IRecordData>() : recordData.OfType<IRecordData>();
        public IRecordData GetRecord(int rowIndex) => recordData[rowIndex];

        [Serializable]
        public struct RecordData : IRecordData
        {
            public RecordDataHeader header;
            public RecordDataHeader Header {set => header = value; get => header;}
            public T0 Field0;
            public T1 Field1;
            public T2 Field2;
            public T3 Field3;
            public T4 Field4;
            public T5 Field5;
            public T6 Field6;
            public T7 Field7;
            public T8 Field8;
            public T9 Field9;
            public T10 Field10;
            public T11 Field11;
            public T12 Field12;
            public T13 Field13;
            public T14 Field14;
            public T15 Field15;
            public T16 Field16;
            public T17 Field17;
            public T18 Field18;
            public T19 Field19;
            public T20 Field20;
            public T21 Field21;
            public T22 Field22;
            public T23 Field23;
        }
    }

    [Serializable]
    public struct VariableStruct<T0,T1,T2,T3,T4,T5,T6,T7,T8,T9,T10,T11,T12,T13,T14,T15,T16,T17,T18,T19,T20,T21,T22,T23,T24> : IVariableStruct
    {
        public RecordHeader header;
        public RecordData[] recordData;
        private static Type[] _fieldTypes = new []{typeof(T0),typeof(T1),typeof(T2),typeof(T3),typeof(T4),typeof(T5),typeof(T6),typeof(T7),typeof(T8),typeof(T9),typeof(T10),typeof(T11),typeof(T12),typeof(T13),typeof(T14),typeof(T15),typeof(T16),typeof(T17),typeof(T18),typeof(T19),typeof(T20),typeof(T21),typeof(T22),typeof(T23),typeof(T24)};
        public RecordHeader Header { set => header = value; get => header; }
        public Type[] GetFieldTypes() => _fieldTypes;
        public IEnumerable<IRecordData> Records => recordData == null ? Array.Empty<IRecordData>() : recordData.OfType<IRecordData>();
        public IRecordData GetRecord(int rowIndex) => recordData[rowIndex];

        [Serializable]
        public struct RecordData : IRecordData
        {
            public RecordDataHeader header;
            public RecordDataHeader Header {set => header = value; get => header;}
            public T0 Field0;
            public T1 Field1;
            public T2 Field2;
            public T3 Field3;
            public T4 Field4;
            public T5 Field5;
            public T6 Field6;
            public T7 Field7;
            public T8 Field8;
            public T9 Field9;
            public T10 Field10;
            public T11 Field11;
            public T12 Field12;
            public T13 Field13;
            public T14 Field14;
            public T15 Field15;
            public T16 Field16;
            public T17 Field17;
            public T18 Field18;
            public T19 Field19;
            public T20 Field20;
            public T21 Field21;
            public T22 Field22;
            public T23 Field23;
            public T24 Field24;
        }
    }

    [Serializable]
    public struct VariableStruct<T0,T1,T2,T3,T4,T5,T6,T7,T8,T9,T10,T11,T12,T13,T14,T15,T16,T17,T18,T19,T20,T21,T22,T23,T24,T25> : IVariableStruct
    {
        public RecordHeader header;
        public RecordData[] recordData;
        private static Type[] _fieldTypes = new []{typeof(T0),typeof(T1),typeof(T2),typeof(T3),typeof(T4),typeof(T5),typeof(T6),typeof(T7),typeof(T8),typeof(T9),typeof(T10),typeof(T11),typeof(T12),typeof(T13),typeof(T14),typeof(T15),typeof(T16),typeof(T17),typeof(T18),typeof(T19),typeof(T20),typeof(T21),typeof(T22),typeof(T23),typeof(T24),typeof(T25)};
        public RecordHeader Header { set => header = value; get => header; }
        public Type[] GetFieldTypes() => _fieldTypes;
        public IEnumerable<IRecordData> Records => recordData == null ? Array.Empty<IRecordData>() : recordData.OfType<IRecordData>();
        public IRecordData GetRecord(int rowIndex) => recordData[rowIndex];

        [Serializable]
        public struct RecordData : IRecordData
        {
            public RecordDataHeader header;
            public RecordDataHeader Header {set => header = value; get => header;}
            public T0 Field0;
            public T1 Field1;
            public T2 Field2;
            public T3 Field3;
            public T4 Field4;
            public T5 Field5;
            public T6 Field6;
            public T7 Field7;
            public T8 Field8;
            public T9 Field9;
            public T10 Field10;
            public T11 Field11;
            public T12 Field12;
            public T13 Field13;
            public T14 Field14;
            public T15 Field15;
            public T16 Field16;
            public T17 Field17;
            public T18 Field18;
            public T19 Field19;
            public T20 Field20;
            public T21 Field21;
            public T22 Field22;
            public T23 Field23;
            public T24 Field24;
            public T25 Field25;
        }
    }

    [Serializable]
    public struct VariableStruct<T0,T1,T2,T3,T4,T5,T6,T7,T8,T9,T10,T11,T12,T13,T14,T15,T16,T17,T18,T19,T20,T21,T22,T23,T24,T25,T26> : IVariableStruct
    {
        public RecordHeader header;
        public RecordData[] recordData;
        private static Type[] _fieldTypes = new []{typeof(T0),typeof(T1),typeof(T2),typeof(T3),typeof(T4),typeof(T5),typeof(T6),typeof(T7),typeof(T8),typeof(T9),typeof(T10),typeof(T11),typeof(T12),typeof(T13),typeof(T14),typeof(T15),typeof(T16),typeof(T17),typeof(T18),typeof(T19),typeof(T20),typeof(T21),typeof(T22),typeof(T23),typeof(T24),typeof(T25),typeof(T26)};
        public RecordHeader Header { set => header = value; get => header; }
        public Type[] GetFieldTypes() => _fieldTypes;
        public IEnumerable<IRecordData> Records => recordData == null ? Array.Empty<IRecordData>() : recordData.OfType<IRecordData>();
        public IRecordData GetRecord(int rowIndex) => recordData[rowIndex];

        [Serializable]
        public struct RecordData : IRecordData
        {
            public RecordDataHeader header;
            public RecordDataHeader Header {set => header = value; get => header;}
            public T0 Field0;
            public T1 Field1;
            public T2 Field2;
            public T3 Field3;
            public T4 Field4;
            public T5 Field5;
            public T6 Field6;
            public T7 Field7;
            public T8 Field8;
            public T9 Field9;
            public T10 Field10;
            public T11 Field11;
            public T12 Field12;
            public T13 Field13;
            public T14 Field14;
            public T15 Field15;
            public T16 Field16;
            public T17 Field17;
            public T18 Field18;
            public T19 Field19;
            public T20 Field20;
            public T21 Field21;
            public T22 Field22;
            public T23 Field23;
            public T24 Field24;
            public T25 Field25;
            public T26 Field26;
        }
    }

    [Serializable]
    public struct VariableStruct<T0,T1,T2,T3,T4,T5,T6,T7,T8,T9,T10,T11,T12,T13,T14,T15,T16,T17,T18,T19,T20,T21,T22,T23,T24,T25,T26,T27> : IVariableStruct
    {
        public RecordHeader header;
        public RecordData[] recordData;
        private static Type[] _fieldTypes = new []{typeof(T0),typeof(T1),typeof(T2),typeof(T3),typeof(T4),typeof(T5),typeof(T6),typeof(T7),typeof(T8),typeof(T9),typeof(T10),typeof(T11),typeof(T12),typeof(T13),typeof(T14),typeof(T15),typeof(T16),typeof(T17),typeof(T18),typeof(T19),typeof(T20),typeof(T21),typeof(T22),typeof(T23),typeof(T24),typeof(T25),typeof(T26),typeof(T27)};
        public RecordHeader Header { set => header = value; get => header; }
        public Type[] GetFieldTypes() => _fieldTypes;
        public IEnumerable<IRecordData> Records => recordData == null ? Array.Empty<IRecordData>() : recordData.OfType<IRecordData>();
        public IRecordData GetRecord(int rowIndex) => recordData[rowIndex];

        [Serializable]
        public struct RecordData : IRecordData
        {
            public RecordDataHeader header;
            public RecordDataHeader Header {set => header = value; get => header;}
            public T0 Field0;
            public T1 Field1;
            public T2 Field2;
            public T3 Field3;
            public T4 Field4;
            public T5 Field5;
            public T6 Field6;
            public T7 Field7;
            public T8 Field8;
            public T9 Field9;
            public T10 Field10;
            public T11 Field11;
            public T12 Field12;
            public T13 Field13;
            public T14 Field14;
            public T15 Field15;
            public T16 Field16;
            public T17 Field17;
            public T18 Field18;
            public T19 Field19;
            public T20 Field20;
            public T21 Field21;
            public T22 Field22;
            public T23 Field23;
            public T24 Field24;
            public T25 Field25;
            public T26 Field26;
            public T27 Field27;
        }
    }

    [Serializable]
    public struct VariableStruct<T0,T1,T2,T3,T4,T5,T6,T7,T8,T9,T10,T11,T12,T13,T14,T15,T16,T17,T18,T19,T20,T21,T22,T23,T24,T25,T26,T27,T28> : IVariableStruct
    {
        public RecordHeader header;
        public RecordData[] recordData;
        private static Type[] _fieldTypes = new []{typeof(T0),typeof(T1),typeof(T2),typeof(T3),typeof(T4),typeof(T5),typeof(T6),typeof(T7),typeof(T8),typeof(T9),typeof(T10),typeof(T11),typeof(T12),typeof(T13),typeof(T14),typeof(T15),typeof(T16),typeof(T17),typeof(T18),typeof(T19),typeof(T20),typeof(T21),typeof(T22),typeof(T23),typeof(T24),typeof(T25),typeof(T26),typeof(T27),typeof(T28)};
        public RecordHeader Header { set => header = value; get => header; }
        public Type[] GetFieldTypes() => _fieldTypes;
        public IEnumerable<IRecordData> Records => recordData == null ? Array.Empty<IRecordData>() : recordData.OfType<IRecordData>();
        public IRecordData GetRecord(int rowIndex) => recordData[rowIndex];

        [Serializable]
        public struct RecordData : IRecordData
        {
            public RecordDataHeader header;
            public RecordDataHeader Header {set => header = value; get => header;}
            public T0 Field0;
            public T1 Field1;
            public T2 Field2;
            public T3 Field3;
            public T4 Field4;
            public T5 Field5;
            public T6 Field6;
            public T7 Field7;
            public T8 Field8;
            public T9 Field9;
            public T10 Field10;
            public T11 Field11;
            public T12 Field12;
            public T13 Field13;
            public T14 Field14;
            public T15 Field15;
            public T16 Field16;
            public T17 Field17;
            public T18 Field18;
            public T19 Field19;
            public T20 Field20;
            public T21 Field21;
            public T22 Field22;
            public T23 Field23;
            public T24 Field24;
            public T25 Field25;
            public T26 Field26;
            public T27 Field27;
            public T28 Field28;
        }
    }

    [Serializable]
    public struct VariableStruct<T0,T1,T2,T3,T4,T5,T6,T7,T8,T9,T10,T11,T12,T13,T14,T15,T16,T17,T18,T19,T20,T21,T22,T23,T24,T25,T26,T27,T28,T29> : IVariableStruct
    {
        public RecordHeader header;
        public RecordData[] recordData;
        private static Type[] _fieldTypes = new []{typeof(T0),typeof(T1),typeof(T2),typeof(T3),typeof(T4),typeof(T5),typeof(T6),typeof(T7),typeof(T8),typeof(T9),typeof(T10),typeof(T11),typeof(T12),typeof(T13),typeof(T14),typeof(T15),typeof(T16),typeof(T17),typeof(T18),typeof(T19),typeof(T20),typeof(T21),typeof(T22),typeof(T23),typeof(T24),typeof(T25),typeof(T26),typeof(T27),typeof(T28),typeof(T29)};
        public RecordHeader Header { set => header = value; get => header; }
        public Type[] GetFieldTypes() => _fieldTypes;
        public IEnumerable<IRecordData> Records => recordData == null ? Array.Empty<IRecordData>() : recordData.OfType<IRecordData>();
        public IRecordData GetRecord(int rowIndex) => recordData[rowIndex];

        [Serializable]
        public struct RecordData : IRecordData
        {
            public RecordDataHeader header;
            public RecordDataHeader Header {set => header = value; get => header;}
            public T0 Field0;
            public T1 Field1;
            public T2 Field2;
            public T3 Field3;
            public T4 Field4;
            public T5 Field5;
            public T6 Field6;
            public T7 Field7;
            public T8 Field8;
            public T9 Field9;
            public T10 Field10;
            public T11 Field11;
            public T12 Field12;
            public T13 Field13;
            public T14 Field14;
            public T15 Field15;
            public T16 Field16;
            public T17 Field17;
            public T18 Field18;
            public T19 Field19;
            public T20 Field20;
            public T21 Field21;
            public T22 Field22;
            public T23 Field23;
            public T24 Field24;
            public T25 Field25;
            public T26 Field26;
            public T27 Field27;
            public T28 Field28;
            public T29 Field29;
        }
    }

    [Serializable]
    public struct VariableStruct<T0,T1,T2,T3,T4,T5,T6,T7,T8,T9,T10,T11,T12,T13,T14,T15,T16,T17,T18,T19,T20,T21,T22,T23,T24,T25,T26,T27,T28,T29,T30> : IVariableStruct
    {
        public RecordHeader header;
        public RecordData[] recordData;
        private static Type[] _fieldTypes = new []{typeof(T0),typeof(T1),typeof(T2),typeof(T3),typeof(T4),typeof(T5),typeof(T6),typeof(T7),typeof(T8),typeof(T9),typeof(T10),typeof(T11),typeof(T12),typeof(T13),typeof(T14),typeof(T15),typeof(T16),typeof(T17),typeof(T18),typeof(T19),typeof(T20),typeof(T21),typeof(T22),typeof(T23),typeof(T24),typeof(T25),typeof(T26),typeof(T27),typeof(T28),typeof(T29),typeof(T30)};
        public RecordHeader Header { set => header = value; get => header; }
        public Type[] GetFieldTypes() => _fieldTypes;
        public IEnumerable<IRecordData> Records => recordData == null ? Array.Empty<IRecordData>() : recordData.OfType<IRecordData>();
        public IRecordData GetRecord(int rowIndex) => recordData[rowIndex];

        [Serializable]
        public struct RecordData : IRecordData
        {
            public RecordDataHeader header;
            public RecordDataHeader Header {set => header = value; get => header;}
            public T0 Field0;
            public T1 Field1;
            public T2 Field2;
            public T3 Field3;
            public T4 Field4;
            public T5 Field5;
            public T6 Field6;
            public T7 Field7;
            public T8 Field8;
            public T9 Field9;
            public T10 Field10;
            public T11 Field11;
            public T12 Field12;
            public T13 Field13;
            public T14 Field14;
            public T15 Field15;
            public T16 Field16;
            public T17 Field17;
            public T18 Field18;
            public T19 Field19;
            public T20 Field20;
            public T21 Field21;
            public T22 Field22;
            public T23 Field23;
            public T24 Field24;
            public T25 Field25;
            public T26 Field26;
            public T27 Field27;
            public T28 Field28;
            public T29 Field29;
            public T30 Field30;
        }
    }

    [Serializable]
    public struct VariableStruct<T0,T1,T2,T3,T4,T5,T6,T7,T8,T9,T10,T11,T12,T13,T14,T15,T16,T17,T18,T19,T20,T21,T22,T23,T24,T25,T26,T27,T28,T29,T30,T31> : IVariableStruct
    {
        public RecordHeader header;
        public RecordData[] recordData;
        private static Type[] _fieldTypes = new []{typeof(T0),typeof(T1),typeof(T2),typeof(T3),typeof(T4),typeof(T5),typeof(T6),typeof(T7),typeof(T8),typeof(T9),typeof(T10),typeof(T11),typeof(T12),typeof(T13),typeof(T14),typeof(T15),typeof(T16),typeof(T17),typeof(T18),typeof(T19),typeof(T20),typeof(T21),typeof(T22),typeof(T23),typeof(T24),typeof(T25),typeof(T26),typeof(T27),typeof(T28),typeof(T29),typeof(T30),typeof(T31)};
        public RecordHeader Header { set => header = value; get => header; }
        public Type[] GetFieldTypes() => _fieldTypes;
        public IEnumerable<IRecordData> Records => recordData == null ? Array.Empty<IRecordData>() : recordData.OfType<IRecordData>();
        public IRecordData GetRecord(int rowIndex) => recordData[rowIndex];

        [Serializable]
        public struct RecordData : IRecordData
        {
            public RecordDataHeader header;
            public RecordDataHeader Header {set => header = value; get => header;}
            public T0 Field0;
            public T1 Field1;
            public T2 Field2;
            public T3 Field3;
            public T4 Field4;
            public T5 Field5;
            public T6 Field6;
            public T7 Field7;
            public T8 Field8;
            public T9 Field9;
            public T10 Field10;
            public T11 Field11;
            public T12 Field12;
            public T13 Field13;
            public T14 Field14;
            public T15 Field15;
            public T16 Field16;
            public T17 Field17;
            public T18 Field18;
            public T19 Field19;
            public T20 Field20;
            public T21 Field21;
            public T22 Field22;
            public T23 Field23;
            public T24 Field24;
            public T25 Field25;
            public T26 Field26;
            public T27 Field27;
            public T28 Field28;
            public T29 Field29;
            public T30 Field30;
            public T31 Field31;
        }
    }
#endregion //VariableStructs 
}
