using System;
using System.Linq;
using System.Collections.Generic;
using UnityEngine;

namespace TinyDataTable.Editor
{
    internal static class ExportRecordToCSharp
    {
        public static string Export(
            DataTableBase asset,
            IList<FieldInfo> fieldInfos,
            IList<EnumInfo> enumInfos,
            string className,
            string namespaceName,
            string resourcePath,
            string addressName,
            string assetPath
            )
        {
            CSharpCodeBuilder cb = new CSharpCodeBuilder();
            bool isObsolete = asset != null && asset.EditorFlags.HasFlag( DataTableBase.Flags.Obsolete);
            string onsolete = isObsolete ? "Obsolete" : null;

            var version = typeof(TinyDataTable.DataTableBase).Assembly.GetName().Version;
            
            cb.AddComment($"[TINY_DATA_TABLE][{version}]");
            cb.AddComment("This code was generated by TinyDataTable.");
            cb.AddComment("Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.");

//            cb.AppendLine("#pragma warning disable CS0612");

            var usingImplement = asset?.GetUsingImplement();
            if (usingImplement == null)
            {
                cb.AddUsing("System");
                cb.AddUsing("TinyDataTable");
//                cb.AddUsing("UnityEngine");
//            cb.AddUsing("System.Collections.Generic");
//            cb.AddUsing("System.Runtime.CompilerServices");
//            cb.AddUsing("System.Linq");
            }
            else
            {
                foreach (var impl in usingImplement)
                {
                    cb.AppendLine(impl);
                }
            }

            cb.AppendLineNoIndent("#if UNITY_EDITOR");
            cb.AddUsing("DescriptionAttribute = System.ComponentModel.DescriptionAttribute");
            cb.AppendLineNoIndent("#else");
            cb.AddUsing("DescriptionAttribute = TinyDataTable.Description.DescriptionAttribute");
            cb.AppendLineNoIndent("#endif");
            cb.AppendLine();

            string recordTypeName = $"{className}";
            string enumTypeName = $"{recordTypeName}.Enum";
            string schemaTypeName = $"{recordTypeName}.Schema";
            string idName = "ID";
            string idFullName = $"{recordTypeName}.{idName}";
            
            //Make ID
            using (cb.BeginNamespace(namespaceName))
            {
                //Record ScriptableObject
                cb.AddComment("Record ScriptableObject");
                cb.AddAttribute(onsolete,$"Record(typeof({schemaTypeName}),typeof({enumTypeName}),typeof({idFullName}))");
                using (cb.BeginClass($"{recordTypeName}", inherit: $"DataTableBase<{schemaTypeName}>", isPartial: true))
                {
                    //Record Struct
                    cb.AddComment("Schema struct");
                    cb.AddAttribute(onsolete, "Serializable");
                    using (cb.BeginStruct("Schema", isPartial:false))
                    {
                        if (fieldInfos.Any())
                        {
                            foreach (var field in fieldInfos)
                            {
                                cb.AddAttribute(field.ToBaseAttributeString(true));
                                foreach (var attr in field.ToAttributesString())
                                {
                                    cb.AddAttribute(attr);
                                }

                                cb.AddCode($"public {field.Type.GetCSharpAliasFull()} {field.Name}");
                            }
                        }
                        else
                        {
                            cb.AppendLine($"[SerializeField,HideInInspector,Obsolete]");
                            cb.AppendLine($"private bool __dummy; // dummy for avoiding compile error");
                        }
                    }
                    cb.AppendLine();
                    
                    // Enum
                    cb.AddComment("Enum");
                    cb.AddAttribute(onsolete, "Serializable");
                    using (cb.BeginEnum($"Enum"))
                    {
                        if (asset != null)
                        {
                            var enums = asset.Headers
                                .Select( (header, idx) => (header,idx) )
                                .Where(t=> string.IsNullOrEmpty(t.header.name) is false)
                                .Select( t => (
                                    $"[EnumIndex({t.idx})] {t.header.name}",
                                    $"0x{t.header.id:X8}",
                                    t.header.description,
                                    t.header.obsolete ? "Obsolete" : ""))
                                .ToList();
                            cb.AddEnums(enums);
                            
                            // Obsoletes
                            if (enums.Any() )
                            {
                                var losts = enumInfos
                                    .Where(b => asset.Headers.All(a => a.name != b.Name));
                                if (losts.Any())
                                {
                                    cb.AddComment("Missing");
                                    var lostEnums = losts
                                        .Select(t => (t, asset.Headers.FirstOrDefault(f => f.id == t.Value).name))
                                        .Select(t => (
                                            $"[Missing] {t.t.Name}",
                                            t.name ?? $"Invalid",
                                            string.Empty,
                                            string.IsNullOrEmpty(t.name) || t.name == "Invalid"
                                                ? $"Obsolete(\"Please change to a different.\")"
                                                : $"Obsolete(\"Use {t.name} instead.\")"));
                                    cb.AddEnums(lostEnums);
                                }
                            }
                        }
                        else
                        {
                            cb.AppendLine("[EnumIndex(0)] Invalid = 0x00000000,");
                        }
                    }
                    cb.AppendLine();
                    
                    // ID
                    cb.AddComment("ID");
                    cb.AddAttribute(onsolete,$"ID(typeof({recordTypeName}))", "Serializable");                    
                    using (cb.BeginStruct(idName, inherit: $"IIdentifier", isPartial: true))
                    {
                        var idImplement = "            //If you need to implement it, please write it here.";
                        if (asset != null)
                        {
                            var tmp = asset.GetIDImplement();
                            if (string.IsNullOrEmpty(tmp) is false)
                            {
                                idImplement = tmp;
                            }
                        }
                        cb.AppendLineNoIndent(idImplement);
                    }

                    if (string.IsNullOrEmpty(addressName) is false)
                    {
                        cb.AppendLine();                    
                        cb.AddComment("AddressableName");
                        cb.AddField("string", $"AddressableName = \"{addressName}\"", "public const");
                    }
                    if (string.IsNullOrEmpty(resourcePath) is false)
                    {
                        cb.AppendLine();                    
                        cb.AddComment("ResourcePath");
                        cb.AddField("string", $"ResourcePath = \"{resourcePath}\"", "public const");
                    }
                }
            }   //End of namespace

            return cb.ToString();
        }
    }
}