using System;
using System.Linq;
using System.Collections.Generic;
using UnityEngine;

namespace TinyDataTable.Editor
{
    public static class ExportDataSheetToCSharp
    {
        public static string Export(
//            DataTableAsset asset,
            IRecord record,
            IList<RecordFieldInfo> fields,
            string className,
            string namespaceName,
            string resourcePath,
            string addressName,
            string assetPath
            )
        {
            CSharpCodeBuilder cb = new CSharpCodeBuilder();

            cb.AddComment("[TINY_DATA_TABLE][1.0.0]");
            cb.AddComment("This code is generated by TinyDataTable.");
            cb.AddComment("Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.");
            
            cb.AppendLine("#pragma warning disable CS0612");
            cb.AddUsing("System");
            cb.AddUsing("System.Linq");
            cb.AddUsing("UnityEngine");
            cb.AddUsing("System.Collections.Generic");
            cb.AddUsing("TinyDataTable");
            
            cb.AppendLine();
            
            using (cb.BeginNamespace(namespaceName))
            {
//                cb.AddAttribute(asset.Obsolete ? "Serializable,Obsolete" : "Serializable");

                using (cb.BeginStruct(className,
                           inherit: $"IIdentifier, IEquatable<{className}>, IEquatable<{className}.Enum>",
                           isPartial: true))
                {
                    //Enum
                    using (cb.AddAttribute("Serializable").BeginEnum("Enum"))
                    {
                        if (record != null)
                        {
                            var enums = record.Headers
                                .Select((h, i) => ($"[EnumOrder({i})] {h.name}", $"0x{h.id:X8}", h.description,
                                    h.obsolete ? "Obsolete" : ""))
                                .ToList();
                            cb.AddEnums(enums);
                        }
                        else
                        {
                            cb.AppendLine("[EnumOrder(0)] Invalid = 0x00000000");
                        }
                    }
                    cb.AppendLine();

                    //Record Struct
                    using (cb.AddAttribute("Serializable").BeginStruct("Record" , "private"))
                    {
//                        foreach (var info in data.record.Header.fieldInfos.Zip( data.record.GetFieldTypes() , (info,type) => (info,type) ))
                        if (fields.Any())
                        {
                            foreach (var field in fields)
                            {
                                if (field.obsolete)
                                {
                                    cb.AppendLine("[Obsolete(\"This field is obsolete.\")]");
                                }
                                cb.AddCode($"public {field.type.FullName} {field.name}");
                            }
                        }
                        else
                        {
                            //空の構造体はエラーになるのでダミーを追加しておく
                            cb.AddCode($"[SerializeField,HideInInspector] private bool __dummy");
                        }
                    }
                    cb.AddComment("Record Type");
                    cb.AddCode($"private static Type RecordType => typeof(Record)");
                    cb.AppendLine();

                    //プライベートメンバー
                    cb.AddComment("Private member");
                    cb.AddField("DataTableAsset", "_dataTable", "private static");
                    cb.AddField("Record[]", "_recordArray", "private static");
                    
                    if (string.IsNullOrEmpty(addressName) is false)
                    {
                        cb.AddField("string", $"AddressableName = \"{addressName}\"", "public const");
                    }
                    if (string.IsNullOrEmpty(resourcePath) is false)
                    {
                        cb.AddField("string", $"ResourcePath = \"{resourcePath}\"", "public const");
                    }
                    cb.AppendLine();

                    //メンバー
                    cb.AddComment("Member");
                    cb.AddAttribute("SerializeField");
                    cb.AddField("Enum", "_value", "private");
                    cb.AddAttribute("NonSerialized");
                    cb.AddField("int", "_index", "private");
                    cb.AppendLine();

                    //コンストラクター
                    cb.AddComment("Constructor");
                    using (cb.BeginConstructor(className, "Enum value, int index", "private"))
                    {
                        cb.AddCode("this._value = value");
                        cb.AddCode("this._index = index");
                    }

                    cb.AppendLine();
                    cb.AddComment("Constructor");
                    using (cb.BeginConstructor(className, "Enum value",
                               "public", "this(value, EnumToIndex(value))"))
                    {
                    }

                    cb.AppendLine();
                    cb.AddComment("Constructor");
                    using (cb.BeginConstructor(className, $"{className} value",
                               "public", "this(value._value, value._index)"))
                    {
                    }

                    cb.AppendLine();

#if false                    
                    //　Prepare
                    if (string.IsNullOrEmpty(addressName) is false)
                    {
                        cb.AddComment("Prepare(Addressables)");
                        using (cb.BeginMethod("void", "Prepare", "", "public static"))
                        {
                            if (string.IsNullOrEmpty(addressName) is false)
                            {
                                using (cb.BeginIf("_dataTable is null"))
                                {
                                    cb.AddCode(
                                        "var op = UnityEngine.AddressableAssets.Addressables.LoadAssetAsync<DataTableAsset>(_assetPath)");
                                    cb.AddCode("DataTableAsset prefab = op.WaitForCompletion()");
                                    cb.AddCode("_dataTable = prefab");
                                }
                            }
                        }
                    }
                    else if (string.IsNullOrEmpty(resourcePath) is false)
                    {
                        cb.AddComment("Prepare(Resources)");
                        using (cb.BeginMethod("void", "Prepare", "", "public static"))
                        {
                            using (cb.BeginIf("_dataTable is null"))
                            {
                                cb.AddCode($"var prefab = UnityEngine.Resources.Load<DataTableAsset>(_assetPath)");
                                cb.AddCode("_dataTable = prefab");
                            }
                        }
                    }
                    else
                    {
                        cb.AddComment("Prepare");
                        using (cb.BeginMethod("void", "Prepare", "", "public static"))
                        {
                        }
                    }
                    cb.AppendLine();
                    
                    cb.AddComment("Terminate");
                    using (cb.BeginMethod("void", "Terminate", "", "public static"))
                    {
                        using (cb.BeginIf("_dataTable != null"))
                        {
                            cb.AddCode("_dataTable = null");
                            cb.AddCode("_recordArray = null");
                        }
                    }
                    cb.AppendLine();
#endif
                    cb.AddComment("Data Bind(Call for DataTableAsset.OnEnable by reflrection)");
                    using (cb.BeginMethod("void", "BindAsset", "DataTableAsset tableAsset", "private static"))
                    {
                        cb.AddCode("_dataTable = tableAsset");
                        cb.AddCode("_recordArray = _dataTable == null ? null : (Record[])_dataTable.Record.Data");
                    }
                    cb.AppendLine();
                    
                    
                    //Index
                    cb.AddComment("Index of this ID");
                    using (cb.BeginBlock("public int Index"))
                    {
                        using (cb.BeginBlock("get"))
                        {
                            using (cb.BeginIf("_index == 0"))
                            {
                                using (cb.BeginIf("_value == Enum.Invalid"))
                                {
                                    cb.AddCode("return 0");
                                }

                                cb.AddCode("_index = EnumToIndex(_value)");
                            }

                            cb.AddCode("return _index");
                        }
                    }

                    //ValidIDList.Lengthで代用できるのでとりあえずオミット
//                    cb.AddComment("Size of record");
//                    cb.AddCode($"public static int Size => {data.Header.RowData.Length}");
                    cb.AddComment("Valid records");
                    cb.AddCode($"public static IReadOnlyCollection<{className}> ValidIDList => _validIDs");
                    cb.AddComment("Valid Enums");
                    cb.AddCode($"public static IReadOnlyCollection<{className}.Enum> ValidEnumList => _validEnums");
                    cb.AddComment("Is this record is valid");
                    cb.AddCode($"public bool IsValid => _validEnums.Contains( _value )");
                    cb.AppendLine();

                    cb.AddComment("propieries");
                    if (record != null)
                    {
                        foreach (var (header, idx) in record.Headers.Select((header, idx) => (header, idx)))
                        {
                            var name = header.name;
                            var index = idx;
                            if (header.obsolete)
                            {
                                cb.AppendLine("[Obsolete]");
                            }

                            cb.AddCode($"public static readonly {className} {name} = new (Enum.{name}, {index})");
                        }
                    }
                    else
                    {
                        cb.AddCode($"public static readonly {className} Invalid = new (Enum.Invalid, 0)");
                    }
                    cb.AppendLine();

                    //フィールドプロパティ
                    //関数呼び出しを避けるためにインラインで３項演算子を使う
                    cb.AddComment($"filed propieries");
                    foreach (var field in fields)
                    {
                        if (field.obsolete)
                        {
                            cb.AppendLine("[Obsolete]");
                        }
                        var typename = field.type.FullName;
                        var left = $"public {typename} {field.name}";
                        var right = $"_recordArray[_index > 0 ? _index : Index].{field.name}";
                        cb.AddCode($"{left} => {right}");
                    }
                    cb.AppendLine();
                    
                    //operators
                    cb.AddComment("operators");
                    cb.AddCode($"public bool Equals({className} other) => _value == other._value");
                    cb.AddCode($"public bool Equals({className}.Enum other) => _value == other");
                    cb.AddCode($"public override bool Equals(object obj) => obj is {className} other && Equals(other)");
                    cb.AddCode($"public override int GetHashCode() => (int)_value");
                    cb.AddCode($"public override string ToString() => _value.ToString()");
                    cb.AddCode($"public static bool operator ==({className} left, {className} right) => left.Equals(right)");
                    cb.AddCode($"public static bool operator !=({className} left, {className} right) => !left.Equals(right)");
                    cb.AddCode($"public static bool operator ==({className} left, {className}.Enum right) => left.Equals(right)");
                    cb.AddCode($"public static bool operator !=({className} left, {className}.Enum right) => !left.Equals(right)");
                    
  //                  cb.AddCode($"public static bool operator ==({className} left, {className} right) => left._value == right._value");
  //                  cb.AddCode($"public static bool operator !=({className} left, {className} right) => left._value != right._value");
  //                  cb.AddCode($"public static bool operator ==({className} left, {className}.Enum right) => left._value == right");
  //                  cb.AddCode($"public static bool operator !=({className} left, {className}.Enum right) => left._value != right");
  //                  cb.AddCode($"public static bool operator ==({className}.Enum left, {className} right) => left == right._value");
  //                  cb.AddCode($"public static bool operator !=({className}.Enum left, {className} right) => left != right._value");
                    cb.AddCode($"public static implicit operator {className}({className}.Enum value) => new {className}(value)");
                    cb.AddCode($"public static implicit operator {className}.Enum({className} value) => value._value");
                    cb.AppendLine();
                    
                    //静的テーブル
                    cb.AddComment("static id table");
                    var valids = record == null ?
                        Array.Empty<RecordDataHeader>() :
                        record.Headers.Where(h => h.id > 0 && h.obsolete is false).ToArray();
                    if (valids.Any())
                    {
                        using (cb.BeginBlock($"private static readonly {className}[] _validIDs = new[]").Footer(";"))
                        {
                            foreach (var header in valids)
                            {
                                if (header.obsolete is false && header.id > 0)
                                {
                                    cb.AppendLine($"{className}.{header.name},");
                                }
                            }
                        }
                    }
                    else
                    {
                        cb.AddCode(($"private static readonly {className}[] _validIDs = Array.Empty<{className}>()"));
                    }
                    cb.AppendLine();                    
                    
                    cb.AddComment("static enum table");
                    if ( valids.Any())
                    {
                        using (cb.BeginBlock($"private static readonly {className}.Enum[] _validEnums = new[]").Footer(";"))
                        {
                            foreach (var header in valids)
                            {
                                cb.AppendLine($"Enum.{header.name},");
                            }
                        }
                    }
                    else
                    {
                        cb.AddCode(($"private static readonly {className}.Enum[] _validEnums = Array.Empty<{className}.Enum>()"));
                    }
                    cb.AppendLine();
                    
                    //EnumをIndexに変換するメソッド（静的にテーブル展開されるので高速）
                    cb.AddComment("Enum to index");
                    
                    using (cb.BeginBlock("private static int EnumToIndex(Enum value) => value switch").Footer(";"))
                    {
                        if (record != null)
                        {
                            foreach (var (header, idx) in record.Headers.Select((header, idx) => (header, idx)))
                            {
                                cb.AppendLine($"Enum.{header.name} => {idx},");
                            }
                        }
                        else
                        {
                            cb.AppendLine($"Enum.Invalid => 0,");
                        }
                        cb.AppendLine($"_ => 0");
                    }
                    cb.AppendLine();
                    
#if false                    
                    cb.AddComment("AssetTags");
                    using (cb.BeginBlock("private static readonly string[] _assetTags = new string[]").Footer(";"))
                    {
                        var tags = string.Join(",", asset.Tags.Select(t=>$"\"{t}\"") );
                        cb.AppendLine(tags);                        
                    }
                    cb.AddCode("public static bool HasTag(string tag) => _assetTags.Contains(tag)");
                    cb.AppendLine();
#endif                    
                    using (cb.BeginIfdef("UNITY_EDITOR"))
                    {
#if false                        
                        if (asset.InitializeOnLoadEditor)
                        {
                            cb.AddAttribute("UnityEditor.InitializeOnLoadMethod");
                            using (cb.BeginBlock("private static void InitializeOnLoadEditor()"))
                            {
                                using (cb.BeginBlock("UnityEditor.EditorApplication.delayCall += () =>").Footer(";"))
                                {
                                    cb.AddCode($"UnityEditor.AssetDatabase.LoadAssetAtPath<DataTableAsset>(\"{assetPath}\");");
                                }
                            }
                        }
#endif                        
                        //プロパティドロワー（仮）
                        cb.AppendLine($"[UnityEditor.CustomPropertyDrawer(typeof({className}))]");
                        using (cb.BeginClass($"{className}PropertyDrawer" , "private" ,$"TinyDataTable.Editor.IDPropertyDrawerBase<{className}.Enum>" ))
                        {
                        }
                    }
                }    //End of struct
            }   //End of namespace

            return cb.ToString();
        }
    }
}