using System;
using System.Linq;
using System.Collections.Generic;
using UnityEngine;

namespace TinyDataTable.Editor
{
    internal static class ExportRecordToCSharp
    {
        public static string Export(
            DataTableRecordBase recordAsset,
            IList<FieldInfo> fields,
            string className,
            string namespaceName,
            string resourcePath,
            string addressName,
            string assetPath
            )
        {
            CSharpCodeBuilder cb = new CSharpCodeBuilder();
            bool isObsolete = recordAsset != null && recordAsset.IsObsolete;
            string onsolete = isObsolete ? "Obsolete" : null;

            cb.AddComment("[TINY_DATA_TABLE][1.0.0]");
            cb.AddComment("This code was generated by TinyDataTable.");
            cb.AddComment("Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.");

            cb.AppendLine("#pragma warning disable CS0612");
            cb.AddUsing("System");
            cb.AddUsing("System.Collections.Generic");
            cb.AddUsing("System.Runtime.CompilerServices");
            cb.AddUsing("System.Linq");
            cb.AddUsing("UnityEngine");
            cb.AddUsing("TinyDataTable");
            cb.AppendLineNoIndent("#if UNITY_EDITOR");
            cb.AddUsing("DescriptionAttribute = System.ComponentModel.DescriptionAttribute");
            cb.AppendLineNoIndent("#else");
            cb.AddUsing("DescriptionAttribute = TinyDataTable.Description.DescriptionAttribute");
            cb.AppendLineNoIndent("#endif");
            cb.AppendLine();

            var recordClassName = $"{className}Record";
            string enumName = $"{recordClassName}.Enum";
            string schemaName = $"{recordClassName}.Schema";
            string idFullName = $"{recordClassName}.ID";
            string idName = "ID";
            
            //Make ID
            using (cb.BeginNamespace(namespaceName))
            {
                //Record ScriptableObject
                cb.AddComment("Record ScriptableObject");
                cb.AddAttribute(onsolete,$"Record(typeof({schemaName}),typeof({enumName}),typeof({idFullName}),\"{className}\")");
                using (cb.BeginClass($"{recordClassName}", inherit: $"DataTableRecordBase<{schemaName},{enumName}>", isPartial: true))
                {
                    //Record Struct
                    cb.AddComment("Record");
                    cb.AddAttribute(onsolete, "Serializable");
                    using (cb.BeginStruct("Schema", isPartial:true))
                    {
                        if (fields.Any())
                        {
                            foreach (var field in fields)
                            {
                                cb.AddAttribute(field.ToBaseAttributeString(true));
                                foreach (var attr in field.ToAttributesString())
                                {
                                    cb.AddAttribute(attr);
                                }

                                cb.AddCode($"public {field.Type.GetCSharpAliasFull()} {field.Name}");
                            }
                        }
                        else
                        {
                            cb.AppendLine($"[SerializeField,HideInInspector,Obsolete]");
                            cb.AppendLine($"public bool __dummy; // dummy for avoiding compile error");
                        }
                    }
                    cb.AppendLine();
                    
                    // Enum
                    cb.AddComment("Enum");
                    cb.AddAttribute(onsolete, "Serializable");
                    using (cb.BeginEnum($"Enum : Int32"))
                    {
                        if (recordAsset != null)
                        {
                            var enums = recordAsset.Headers
                                .Where(h=> string.IsNullOrEmpty(h.name) is false)
                                .Select((h, i) => (
                                    $"[EnumOrder({i})] {h.name}",
                                    $"0x{h.id:X8}",
                                    h.description,
                                    h.obsolete ? "Obsolete" : ""))
                                .ToList();
                            cb.AddEnums(enums);
                        }
                        else
                        {
                            cb.AppendLine("[EnumOrder(0)] Invalid = 0x00000000,");
                        }
                    }
                    cb.AppendLine();
                    
                    // ID
                    cb.AddComment("ID");
                    cb.AddAttribute(onsolete,$"ID(typeof({recordClassName}),typeof({recordClassName}.Enum))", "Serializable");                    
                    using (cb.BeginStruct(idName, inherit: $"IIdentifier", isPartial: true))
                    {
                        cb.AddComment("...");
                    }

                    if (string.IsNullOrEmpty(addressName) is false)
                    {
                        cb.AppendLine();                    
                        cb.AddComment("AddressableName");
                        cb.AddField("string", $"AddressableName = \"{addressName}\"", "public const");
                    }
                    if (string.IsNullOrEmpty(resourcePath) is false)
                    {
                        cb.AppendLine();                    
                        cb.AddComment("ResourcePath");
                        cb.AddField("string", $"ResourcePath = \"{resourcePath}\"", "public const");
                    }
                }
                cb.AppendLine();

                using (cb.BeginRegion("SorceGenerator"))
                using (cb.BeginClass($"{recordClassName}", isPartial: true))
                {
                    using (cb.BeginStruct(idName, isPartial: true))
                    {                
                        //フィールドプロパティ
                        //関数呼び出しを避けるためにインラインで３項演算子を使う
                        cb.AddComment($"filed propieries");
                        foreach (var field in fields)
                        {
                            cb.AddAttribute(field.ToBaseAttributeString(false));
                            
                            var typename = field.Type.GetCSharpAliasFull();
                            var left = $"public {typename} {field.Name}";
                            var right = $"_recordArray[Index].{field.Name}";
    #if true
                            cb.AddCode($"{left} => {right}");
    #else
                            using (cb.BeginBlock($"public {typename} {field.name}"))
                            {
                                cb.AppendLine("[System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]");      
                                cb.AddCode($"get => {right}");                            
                            }
    #endif
                        }
                        cb.AppendLine();
           

                        

    //                    cb.AppendLine();
             
    #if false                        
                        using (cb.BeginIfdef("UNITY_EDITOR"))
                        {
                            if (asset.InitializeOnLoadEditor)
                            {
                                cb.AddAttribute("UnityEditor.InitializeOnLoadMethod");
                                using (cb.BeginBlock("private static void InitializeOnLoadEditor()"))
                                {
                                    using (cb.BeginBlock("UnityEditor.EditorApplication.delayCall += () =>").Footer(";"))
                                    {
                                        cb.AddCode($"UnityEditor.AssetDatabase.LoadAssetAtPath<DataTableAsset>(\"{assetPath}\");");
                                    }
                                }
                            }
                        }
    #endif                                                
                    }  //End of struct       
                }   //End of class
            }   //End of namespace

            return cb.ToString();
        }
    }
}