name: Deploy UPM Branch

on:
  push:
    branches:
      - main # mainに何かプッシュされたら何でも動くように一時変更
  workflow_dispatch: # 🌟これを追加（GitHubの画面から手動で実行できるようになります）

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Test Message
        run: echo "GitHub Actions is working!"