name: Deploy UPM Branch

on:
  push:
    branches:
      - main
    paths:
      - 'com.sakana3.tinydatatable/**' # このフォルダが変わった時だけ自動で動く
  workflow_dispatch: # 🌟もし自動で動かなくても、Actions画面から手動でいつでも実行できます！

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Subtree split to upm branch
        run: |
          git subtree split --prefix=com.sakana3.tinydatatable --branch upm-deploy
          
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          
          git push origin upm-deploy:upm --force